### ISSUE TITLE
How to clear screen? Bugs spotted.

### ISSUE THREAD

**Issue by manhnt9** [GPUOpen-LibrariesAndSDKs/V-EZ#45] opened 2018-09-27 17:18 UTC
Hi, I'm using V-EZ for a simple example: clearing screen to a specific color.
Here is my command buffer generation.
I only create and bind 1 color attachment for the framebuffer.
```cpp
void CVulkanDriver::createCommandBuffer()
{
  // Get the graphics queue handle.
  vezGetDeviceGraphicsQueue(VKDevice, 0, &GraphicsQueue);

  // Create a command buffer handle.
  VezCommandBufferAllocateInfo allocInfo = {};
  allocInfo.queue = GraphicsQueue;
  allocInfo.commandBufferCount = 1;
  if (vezAllocateCommandBuffers(VKDevice, &allocInfo, &CommandBuffer) != VK_SUCCESS)
  {
    SDL_LogError(SDL_LOG_CATEGORY_RENDER, "vezAllocateCommandBuffers failed");
    exit(1);
  }

  // Begin command buffer recording.
  if (vezBeginCommandBuffer(CommandBuffer, VK_COMMAND_BUFFER_USAGE_SIMULTANEOUS_USE_BIT) != VK_SUCCESS)
  {
    SDL_LogError(SDL_LOG_CATEGORY_RENDER, "vezBeginCommandBuffer failed");
    exit(1);
  }

  // Set the viewport state and dimensions.
  auto width = Device.getWidth();
  auto height = Device.getHeight();
  
  VkViewport viewport = { 0.0f, 0.0f, static_cast<float>(width), static_cast<float>(height), 0.0f, 1.0f };
  VkRect2D scissor = { { 0, 0 },{ static_cast<uint32_t>(width), static_cast<uint32_t>(height) } };
  vezCmdSetViewport(0, 1, &viewport);
  vezCmdSetScissor(0, 1, &scissor);
  vezCmdSetViewportState(1);

  VkClearColorValue clearColor = {
    { 0.4f, 0.6f, 0.9f, 1.0f } // R, G, B, A
  };

  // Define clear values for the swapchain's color and depth attachments.
  // std::array<VezAttachmentReference, 2> attachmentReferences = {};
  std::array<VezAttachmentReference, 1> attachmentReferences = {};
  attachmentReferences[0].clearValue.color = clearColor;
  attachmentReferences[0].loadOp = VK_ATTACHMENT_LOAD_OP_CLEAR;
  attachmentReferences[0].storeOp = VK_ATTACHMENT_STORE_OP_STORE;
  // attachmentReferences[1].clearValue.depthStencil.depth = 1.0f;
  // attachmentReferences[1].loadOp = VK_ATTACHMENT_LOAD_OP_CLEAR;
  // attachmentReferences[1].storeOp = VK_ATTACHMENT_STORE_OP_STORE;

  // Begin a render pass.
  VezRenderPassBeginInfo beginInfo = {};
  beginInfo.framebuffer = Framebuffer.handle;
  beginInfo.attachmentCount = static_cast<uint32_t>(attachmentReferences.size());
  beginInfo.pAttachments = attachmentReferences.data();
  vezCmdBeginRenderPass(&beginInfo);

  // Bind the pipeline and associated resources.
  vezCmdBindPipeline(BasicPipeline.pipeline);
  // vezCmdBindBuffer(m_uniformBuffer, 0, VK_WHOLE_SIZE, 0, 0, 0);
  // vezCmdBindImageView(ImageView, Sampler, 0, 1, 0);

  // Set depth stencil state.
  // VezPipelineDepthStencilState depthStencilState = {};
  // depthStencilState.depthTestEnable = VK_TRUE;
  // depthStencilState.depthWriteEnable = VK_TRUE;
  // depthStencilState.depthCompareOp = VK_COMPARE_OP_LESS_OR_EQUAL;
  // vezCmdSetDepthStencilState(&depthStencilState);

  // Bind the vertex buffer and index buffers.
  // VkDeviceSize offset = 0;
  // vezCmdBindVertexBuffers(0, 1, &m_vertexBuffer, &offset);
  // vezCmdBindIndexBuffer(m_indexBuffer, 0, VK_INDEX_TYPE_UINT32);

  // Draw the quad.
  // vezCmdDrawIndexed(6, 1, 0, 0, 0);

  // End the render pass.
  vezCmdEndRenderPass();

  // End command buffer recording.
  if (vezEndCommandBuffer() != VK_SUCCESS)
  {
    SDL_LogError(SDL_LOG_CATEGORY_RENDER, "vezEndCommandBuffer failed");
    exit(1);
  }
}
```

**Comment by SilvanVR** [comment] 2018-09-27 19:44
I had the same issue and was confused until i found out that V-EZ does all the pipeline binding etc. right before a draw call. This means the screen will not be cleared via a render-renderpass if you have zero draw calls. However, i believe you can use the vkCmdClearColorImage command on the image associated with the swapchain to clear it manually. Soconne, you should consider a little sidemark in the doc about that :-)

**Comment by manhnt9** [comment] 2018-09-28 03:16
Solved using  
```cpp
vezCmdClearColorImage(Framebuffer.colorImage, &clearColor, 1, &range);
```
Reference: Software Rasterization sample

**Comment by manhnt9** [comment] 2018-10-01 00:46
Found out that it is better to use clearValue for VezAttachmentReference instead of `vezCmdClearColorImage`
I was careless for not using docs.
https://gpuopen-librariesandsdks.github.io/V-EZ/#_begin_a_render_pass

**Comment by manhnt9** [comment] 2018-10-01 01:41
Anyways, after removing vezCmdClearColorImage, the screen becomes black.
I think 
```cpp
attachmentReferences[0].clearValue.color = clearColor;
```
should work out of the box?

**Comment by manhnt9** [comment] 2018-10-01 01:43
My current code:
```cpp
void CVulkanDriver::createCommandBuffer()
{
  // Get the graphics queue handle.
  vezGetDeviceGraphicsQueue(VKDevice, 0, &GraphicsQueue);

  // Create a command buffer handle.
  VezCommandBufferAllocateInfo allocInfo = {};
  allocInfo.queue = GraphicsQueue;
  allocInfo.commandBufferCount = 1;
  if (vezAllocateCommandBuffers(VKDevice, &allocInfo, &CommandBuffer) != VK_SUCCESS)
  {
    SDL_LogError(SDL_LOG_CATEGORY_RENDER, "vezAllocateCommandBuffers failed");
    exit(1);
  }

  // Set the viewport state and dimensions.
  auto width = Device.getWidth();
  auto height = Device.getHeight();
  
  // VkViewport viewport = { 0.0f, 0.0f, static_cast<float>(width), static_cast<float>(height), 0.0f, 1.0f };
  // VkRect2D scissor = { { 0, 0 },{ static_cast<uint32_t>(width), static_cast<uint32_t>(height) } };
  // vezCmdSetViewport(0, 1, &viewport);
  // vezCmdSetScissor(0, 1, &scissor);
  // vezCmdSetViewportState(1);

  VkClearColorValue clearColor = {
    { 1.f, 0.f, 0.f, 1.0f } // R, G, B, A
  };

  // Begin command buffer recording.
  if (vezBeginCommandBuffer(CommandBuffer, VK_COMMAND_BUFFER_USAGE_SIMULTANEOUS_USE_BIT) != VK_SUCCESS)
  {
    SDL_LogError(SDL_LOG_CATEGORY_RENDER, "vezBeginCommandBuffer failed");
    exit(1);
  }

  // Define clear values for the swapchain's color and depth attachments.
  std::array<VezAttachmentReference, 2> attachmentReferences = {};
  attachmentReferences[0].clearValue.color = clearColor;
  attachmentReferences[0].loadOp = VK_ATTACHMENT_LOAD_OP_CLEAR;
  attachmentReferences[0].storeOp = VK_ATTACHMENT_STORE_OP_STORE;
  attachmentReferences[1].clearValue.depthStencil.depth = 1.0f;
  attachmentReferences[1].loadOp = VK_ATTACHMENT_LOAD_OP_CLEAR;
  attachmentReferences[1].storeOp = VK_ATTACHMENT_STORE_OP_STORE;

  // VezImageSubresourceRange range = {};
  // range.layerCount = 1;
  // range.levelCount = 1;
  // vezCmdClearColorImage(Framebuffer.colorImage, &clearColor, 1, &range);

  // // Begin a render pass.
  VezRenderPassBeginInfo beginInfo = {};
  beginInfo.framebuffer = Framebuffer.handle;
  beginInfo.attachmentCount = static_cast<uint32_t>(attachmentReferences.size());
  beginInfo.pAttachments = attachmentReferences.data();
  vezCmdBeginRenderPass(&beginInfo);

  // Bind the pipeline and associated resources.
  vezCmdBindPipeline(BasicPipeline.pipeline);
  vezCmdBindImageView(Framebuffer.colorImageView, VK_NULL_HANDLE, 0, 2, 0);

  // End the render pass.
  vezCmdEndRenderPass();

  // End command buffer recording.
  if (vezEndCommandBuffer() != VK_SUCCESS)
  {
    SDL_LogError(SDL_LOG_CATEGORY_RENDER, "vezEndCommandBuffer failed");
    exit(1);
  }
}
```

**Comment by manhnt9** [comment] 2018-10-01 01:45
@Twanks1 Ah I understood what you've said before. This should be an issue.

**Comment by manhnt9** [comment] 2018-10-01 01:51
And calling 
```cpp
vezCmdClearColorImage(Framebuffer.colorImage, &clearColor, 1, &range);
```
makes the validation layer print out:

DS(ERROR): object: 0x5607038a2f78 type: 6 location: 2698 msg_code: 6: Object: 0x5607038a2f78 | Cannot submit cmd buffer using image (0xd) [sub-resource: aspectMask 0x1 array layer 0, mip level 0], with layout VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL when first use is VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL.

**Comment by manhnt9** [comment] 2018-10-01 02:00
Another try
After creating swapchain, I obtain images like this:
```cpp
  result = vezCreateSwapchain(VKDevice, &swapchainCreateInfo, &Swapchain);
  if (result != VK_SUCCESS)
  {
    SDL_LogError(SDL_LOG_CATEGORY_RENDER, "vezCreateSwapchain failed");
    return false;
  }

  auto vkSwapchain = reinterpret_cast<vez::Swapchain*>(Swapchain)->GetHandle();

  uint32_t actualImageCount = 0;
  if (vkGetSwapchainImagesKHR(VKDevice, vkSwapchain, &actualImageCount, nullptr) != VK_SUCCESS || actualImageCount == 0) {
    SDL_LogError(SDL_LOG_CATEGORY_RENDER, "Failed to acquire number of swap chain images");
    exit(1);
  }

  SwapchainImages.resize(actualImageCount);

  if (vkGetSwapchainImagesKHR(VKDevice, vkSwapchain, &actualImageCount, SwapchainImages.data()) != VK_SUCCESS) {
    SDL_LogError(SDL_LOG_CATEGORY_RENDER, "Failed to acquire swap chain images");
    exit(1);
  }
```

Then I in my command buffer generation, before beginning of a render pass:
```cpp
  for (const auto& image : SwapchainImages)
  {
    vezCmdClearColorImage(image, &clearColor, 1, &range);
  }
```
This produces a black screen while it should be red.

**Comment by soconne** [comment] 2018-10-02 03:21
In the code example above, where are you creating vkSwapchain?  You're using vezCreateSwapchain to create a variable named Swapchain.  But where does vkSwapchain come from?  The VezSwapchain object returned by V-EZ is not compatible with native Vulkan.

**Comment by manhnt9** [comment] 2018-10-02 10:35
@soconne I mis-edited the snippet, vkSwapchain is the Vulkan's swapchain handle.
```cpp
  auto vkSwapchain = reinterpret_cast<vez::Swapchain*>(Swapchain)->GetHandle();
```

**Comment by soconne** [comment] 2018-10-03 17:21
So accessing the native handle of the swapchain within V-EZ is technically not allowed and that's why this does not work.  V-EZ has no knowledge of the VkImage handles you're passing into vezCmdClearColorImage.  The design behind V-EZ was that an application would always, and _only_ render to its own allocated framebuffer.  Then blit this image to the swapchain since rendering directly to the swapchain in the first place is not allowed.

Based on what I've read above, I believe the issue with clearing the framebuffer is not a problem anymore but the validation layer output error is, correct?  I have a fix for this I'll be committing soon.

**Comment by SilvanVR** [comment] 2018-10-03 18:35
I just realized that this issue that when no draw-call was issued the render-pass does not clear anything is related to another bug in my engine where i see garbage on screen. In pseudocode:
```
Bind render-target 0 from camera
    // Here are no draw calls
Bind render-target 0 from PostProcess effect using render-target 0 as input
...
```
Because the renderpass does not clear render-target 0 because there is no draw call the post process gets garbage as input. This should be adresses somehow.
Maybe checking when a command buffer was submitted if a framebuffer was bound and if so bind the corresponding renderpass?

**Comment by manhnt9** [comment] 2018-10-04 00:23
Actually screen clearing is a minor issue for me. I just wanted to do a simple example.
If it's not possible to do it with empty draw call then I can let it be.
It would be great to have a fix for image layout too.

**Comment by manhnt9** [comment] 2018-10-04 04:42
```cpp
vezCmdClearColorImage(Framebuffer.colorImage, &clearColor, 1, &range);
```
is working fine after building with latest commits.

**Closed as completed** 2018-10-04 14:49 UTC

**Comment by JSandusky** [comment] 2019-08-05 22:05
vezCmdClearColorImage (and depth) are still really finicky. The only way I've been able to get them to work is to use them from within an isolated command-buffer and not one that ever begins a render-pass, a bit of a hassle.

```
VUID-vkCmdPipelineBarrier-pMemoryBarriers-01185(ERROR / SPEC): msgNum: 0 - vkCmdPipelineBarrier(): pImageMemBarriers[1].dstAccessMask (0x400) is not supported by dstStageMask (0x400). The Vulkan spec states: Each element of pMemoryBarriers, pBufferMemoryBarriers and pImageMemoryBarriers must not have any access flag included in its dstAccessMask member if that bit is not supported by any of the pipeline stages in dstStageMask, as specified in the table of supported access types. (https://www.khronos.org/registry/vulkan/specs/1.1-extensions/html/vkspec.html#VUID-vkCmdPipelineBarrier-pMemoryBarriers-01185)
```

**Comment by publicrepo** [comment] 2022-07-19 07:04
Sounds like I'm where you were at @JSandusky ...

My plan is to clear the color buffer with `vezCmdClearColorImage()` when no draws would occur in a view, otherwise clear via attachment interface. However, calling `vezCmdClearColorImage()` fails validation from `vkCreateRenderPass()` in `RenderPassCache::CreateRenderPass()`.  @manhnt9 appears to be using, or did use, this very logic in code pasted above in this thread.  (As others note, clearing the color buffer via attachment interface appears to have no effect without draws. That is the main motivation for this usage.)

`Validation Error: [ VUID-VkRenderPassCreateInfo-pDependencies-00838 ] Object 0: VK_NULL_HANDLE, type = VK_OBJECT_TYPE_RENDER_PASS; | MessageID = 0xb2225bf1 | vkCreateRenderPass: Dependency pDependencies[0] specifies a dstStageMask that contains stages (VK_PIPELINE_STAGE_TRANSFER_BIT) that are not part of the Graphics pipeline, as specified by the dstSubpass (= 0) in pipelineBindPoint. The Vulkan spec states: For any element of pDependencies, if the dstSubpass is not VK_SUBPASS_EXTERNAL, all stage flags included in the dstStageMask member of that dependency must be a pipeline stage supported by the pipeline identified by the pipelineBindPoint member of the destination subpass (https://vulkan.lunarg.com/doc/view/1.3.216.0/windows/1.3-extensions/vkspec.html#VUID-VkRenderPassCreateInfo-pDependencies-00838)`

This issue can be easily reproduced in SimpleQuad sample by adding these lines
```
    VkClearColorValue clearColor = {1.0f,0.0f,0.0f,1.0f}; // Red
    VezImageSubresourceRange range = {};
    range.layerCount = 1;
    range.levelCount = 1;
    vezCmdClearColorImage(AppBase::GetColorAttachment(), &clearColor, 1, &range);
```
before the `vezCmdBeginRenderPass(&beginInfo);` code block in SimpleQuad.cpp.

The SoftwareRasterizer sample does not fail because it has no render pass.

I'm new to Vulkan so unsure if my logic is sound or if a flaw exists somewhere.
